# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python CICD

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Test format
        run: |
          python3 -m pip install black
          black --check src/ecsapi

      - name: Test lint
        run: |
          python3 -m pip install flake8
          flake8 src/ecsapi

      - name: Run tests
        run: |
          python3 -m pip install pytest pytest-cov
          pytest --cov


  build:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: Build package
        run: |
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade twine
          python3 -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  pypi-publish:
    runs-on: ubuntu-22.04
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
